services:
  - type: web
    name: my-monolith
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm ci
      cd ../frontend && npm ci && npm run build
    startCommand: npm start
    buildFilter:
      paths:
        - backend/**
        - frontend/**
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: chatApp
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: NODE_VERSION
        value: "22.13.1"
